// prettier-ignore
enum JobOrderActionTypes {
  SET_BOTTOM_SHEET_OPTIONS_JO  = 'jo/SET_BOTTOM_SHEET_OPTIONS_JO',
  SET_DIALOG_DETAIL_JO    = 'jo/SET_DIALOG_DETAIL_JO',

  FETCH_LIST_JO_REQUESTED  = 'jo/FETCH_LIST_JO_REQUESTED',
  FETCH_LIST_JO_LOADING    = 'jo/FETCH_LIST_JO_LOADING',
  FETCH_LIST_JO_FAILURE    = 'jo/FETCH_LIST_JO_FAILURE',
  FETCH_LIST_JO_SUCCESS    = 'jo/FETCH_LIST_JO_SUCCESS',
  SET_ROWS_PER_PAGE_JO        = 'jo/SET_ROWS_PER_PAGE_JO',
  SET_PAGE_LIST_JO            = 'jo/SET_PAGE_LIST_JO',

  CREATE_JO_REQUESTED = 'jo/CREATE_JO_REQUESTED',
  CREATE_JO_LOADING   = 'jo/CREATE_JO_LOADING',
  CREATE_JO_FAILURE   = 'jo/CREATE_JO_FAILURE',
  CREATE_JO_SUCCESS   = 'jo/CREATE_JO_SUCCESS',

  UPDATE_JO_REQUESTED = 'jo/UPDATE_JO_REQUESTED',
  UPDATE_JO_LOADING   = 'jo/UPDATE_JO_LOADING',
  UPDATE_JO_FAILURE   = 'jo/UPDATE_JO_FAILURE',
  UPDATE_JO_SUCCESS   = 'jo/UPDATE_JO_SUCCESS',

  FETCH_JO_BY_ID_REQUESTED = 'jo/FETCH_JO_BY_ID_REQUESTED',
  FETCH_JO_BY_ID_LOADING   = 'jo/FETCH_JO_BY_ID_LOADING',
  FETCH_JO_BY_ID_FAILURE   = 'jo/FETCH_JO_BY_ID_FAILURE',
  FETCH_JO_BY_ID_SUCCESS   = 'jo/FETCH_JO_BY_ID_SUCCESS',

  FETCH_INVOICE_DATA_REQUESTED = 'jo/FETCH_INVOICE_DATA_REQUESTED',
  FETCH_INVOICE_DATA_LOADING   = 'jo/FETCH_INVOICE_DATA_LOADING',
  FETCH_INVOICE_DATA_FAILURE   = 'jo/FETCH_INVOICE_DATA_FAILURE',
  FETCH_INVOICE_DATA_SUCCESS   = 'jo/FETCH_INVOICE_DATA_SUCCESS',

  UPDATE_PAYMENT_STATUS_REQUESTED = 'jo/UPDATE_PAYMENT_STATUS_REQUESTED',
  UPDATE_PAYMENT_STATUS_LOADING   = 'jo/UPDATE_PAYMENT_STATUS_LOADING',
  UPDATE_PAYMENT_STATUS_SUCCESS   = 'jo/UPDATE_PAYMENT_STATUS_SUCCESS',
  UPDATE_PAYMENT_STATUS_FAILURE   = 'jo/UPDATE_PAYMENT_STATUS_FAILURE',

  UPDATE_PRODUCTION_STATUS_REQUESTED  = 'jo/UPDATE_PRODUCTION_STATUS_REQUESTED',
  UPDATE_PRODUCTION_STATUS_LOADING    = 'jo/UPDATE_PRODUCTION_STATUS_LOADING',
  UPDATE_PRODUCTION_STATUS_SUCCESS    = 'jo/UPDATE_PRODUCTION_STATUS_SUCCESS',
  UPDATE_PRODUCTION_STATUS_FAILURE    = 'jo/UPDATE_PRODUCTION_STATUS_FAILURE',

  UPDATE_PERCENTAGE_PROGRESS_REQUESTED  = 'jo/UPDATE_PERCENTAGE_PROGRESS_REQUESTED',
  UPDATE_PERCENTAGE_PROGRESS_LOADING    = 'jo/UPDATE_PERCENTAGE_PROGRESS_LOADING',
  UPDATE_PERCENTAGE_PROGRESS_SUCCESS    = 'jo/UPDATE_PERCENTAGE_PROGRESS_SUCCESS',
  UPDATE_PERCENTAGE_PROGRESS_FAILURE    = 'jo/UPDATE_PERCENTAGE_PROGRESS_FAILURE',

  ADD_NOTES_JO_REQUESTED  = 'jo/ADD_NOTES_JO_REQUESTED',
  ADD_NOTES_JO_LOADING    = 'jo/ADD_NOTES_JO_LOADING',
  ADD_NOTES_JO_SUCCESS    = 'jo/ADD_NOTES_JO_SUCCESS',
  ADD_NOTES_JO_FAILURE    = 'jo/ADD_NOTES_JO_FAILURE',
}

export default JobOrderActionTypes;
