export const fakeUserList = [
  {
    id: 'f24c90bc-5091-43f7-a7f6-648120074591',
    name: 'Tim Gudang 2',
    email: 'timgudang2@yopmail.com',
    photo_url: null,
    role: {
      id: 3,
      name: 'Tim Gudang',
      slug: 'warehouse-team',
      permissions: [
        {
          id: 5,
          name: 'Lihat Inventory',
          code: 'READ_INVENTORY',
          description: null,
        },
        {
          id: 6,
          name: 'Buat Inventory',
          code: 'CREATE_INVENTORY',
          description: null,
        },
        {
          id: 7,
          name: 'Edit Inventory',
          code: 'UPDATE_INVENTORY',
          description: null,
        },
        {
          id: 8,
          name: 'Hapus Inventory',
          code: 'DELETE_INVENTORY',
          description: null,
        },
      ],
      description: null,
    },
    phone_number: null,
    gender: null,
    about: null,
    birthday: null,
    status: 'active',
    created_at: '2022-02-21T08:07:08.000000Z',
    updated_at: null,
  },
  {
    id: 'ed8e74a4-0ace-4636-bf13-365ec445a4cd',
    name: 'Super Admin 2',
    email: 'superadmin2@yopmail.com',
    photo_url: null,
    role: {
      id: 1,
      name: 'Super Admin',
      slug: 'super-admin',
      permissions: [
        {
          id: 1,
          name: 'Lihat Jo',
          code: 'READ_JO',
          description: null,
        },
        {
          id: 2,
          name: 'Buat JO',
          code: 'CREATE_JO',
          description: null,
        },
        {
          id: 3,
          name: 'Edit Jo',
          code: 'UPDATE_JO',
          description: null,
        },
        {
          id: 4,
          name: 'Hapus Jo',
          code: 'DELETE_JO',
          description: null,
        },
        {
          id: 5,
          name: 'Lihat Inventory',
          code: 'READ_INVENTORY',
          description: null,
        },
        {
          id: 6,
          name: 'Buat Inventory',
          code: 'CREATE_INVENTORY',
          description: null,
        },
        {
          id: 7,
          name: 'Edit Inventory',
          code: 'UPDATE_INVENTORY',
          description: null,
        },
        {
          id: 8,
          name: 'Hapus Inventory',
          code: 'DELETE_INVENTORY',
          description: null,
        },
      ],
      description: null,
    },
    phone_number: null,
    gender: null,
    about: null,
    birthday: null,
    status: 'active',
    created_at: '2022-02-21T08:07:08.000000Z',
    updated_at: null,
  },
  {
    id: 'e8fd80b4-1b5a-4562-a525-3cc76c47bf74',
    name: 'Super Admin 1',
    email: 'superadmin1@yopmail.com',
    photo_url: null,
    role: {
      id: 1,
      name: 'Super Admin',
      slug: 'super-admin',
      permissions: [
        {
          id: 1,
          name: 'Lihat Jo',
          code: 'READ_JO',
          description: null,
        },
        {
          id: 2,
          name: 'Buat JO',
          code: 'CREATE_JO',
          description: null,
        },
        {
          id: 3,
          name: 'Edit Jo',
          code: 'UPDATE_JO',
          description: null,
        },
        {
          id: 4,
          name: 'Hapus Jo',
          code: 'DELETE_JO',
          description: null,
        },
        {
          id: 5,
          name: 'Lihat Inventory',
          code: 'READ_INVENTORY',
          description: null,
        },
        {
          id: 6,
          name: 'Buat Inventory',
          code: 'CREATE_INVENTORY',
          description: null,
        },
        {
          id: 7,
          name: 'Edit Inventory',
          code: 'UPDATE_INVENTORY',
          description: null,
        },
        {
          id: 8,
          name: 'Hapus Inventory',
          code: 'DELETE_INVENTORY',
          description: null,
        },
      ],
      description: null,
    },
    phone_number: null,
    gender: null,
    about: null,
    birthday: null,
    status: 'active',
    created_at: '2022-02-21T08:07:08.000000Z',
    updated_at: null,
  },
  {
    id: 'e5d89ee2-f2db-446f-a0e6-94730d00d030',
    name: 'Tim Produksi 1',
    email: 'timproduksi@yopmail.com',
    photo_url: null,
    role: {
      id: 4,
      name: 'Tim Produksi',
      slug: 'production-team',
      permissions: [
        {
          id: 1,
          name: 'Lihat Jo',
          code: 'READ_JO',
          description: null,
        },
        {
          id: 3,
          name: 'Edit Jo',
          code: 'UPDATE_JO',
          description: null,
        },
      ],
      description: null,
    },
    phone_number: null,
    gender: null,
    about: null,
    birthday: null,
    status: 'active',
    created_at: '2022-02-21T08:07:08.000000Z',
    updated_at: null,
  },
  {
    id: 'cda682fb-2680-438e-bdae-a5f99c0aa12d',
    name: 'Tim Produksi 2',
    email: 'timproduksi2@yopmail.com',
    photo_url: null,
    role: {
      id: 4,
      name: 'Tim Produksi',
      slug: 'production-team',
      permissions: [
        {
          id: 1,
          name: 'Lihat Jo',
          code: 'READ_JO',
          description: null,
        },
        {
          id: 3,
          name: 'Edit Jo',
          code: 'UPDATE_JO',
          description: null,
        },
      ],
      description: null,
    },
    phone_number: null,
    gender: null,
    about: null,
    birthday: null,
    status: 'active',
    created_at: '2022-02-21T08:07:08.000000Z',
    updated_at: null,
  },
  {
    id: 'bedd459a-f895-4a9f-b87d-262e27cc7913',
    name: 'Customer Service',
    email: 'cs@yopmail.com',
    photo_url: null,
    role: {
      id: 8,
      name: 'Customer Service (CS)',
      slug: 'customer-service',
      permissions: [
        {
          id: 1,
          name: 'Lihat Jo',
          code: 'READ_JO',
          description: null,
        },
        {
          id: 2,
          name: 'Buat JO',
          code: 'CREATE_JO',
          description: null,
        },
        {
          id: 3,
          name: 'Edit Jo',
          code: 'UPDATE_JO',
          description: null,
        },
        {
          id: 4,
          name: 'Hapus Jo',
          code: 'DELETE_JO',
          description: null,
        },
      ],
      description: null,
    },
    phone_number: null,
    gender: null,
    about: null,
    birthday: null,
    status: 'active',
    created_at: '2022-02-21T08:07:09.000000Z',
    updated_at: null,
  },
  {
    id: 'be7f66ad-65a2-42b2-b5af-8bb4a0d3249c',
    name: 'Admin 2',
    email: 'admin2@yopmail.com',
    photo_url: null,
    role: {
      id: 2,
      name: 'Admin',
      slug: 'admin',
      permissions: [],
      description: null,
    },
    phone_number: null,
    gender: null,
    about: null,
    birthday: null,
    status: 'active',
    created_at: '2022-02-21T08:07:08.000000Z',
    updated_at: null,
  },
  {
    id: '9dc2ae98-4934-44eb-bd89-1af59eb9cf50',
    name: 'Admin 1',
    email: 'admin1@yopmail.com',
    photo_url: null,
    role: {
      id: 2,
      name: 'Admin',
      slug: 'admin',
      permissions: [],
      description: null,
    },
    phone_number: null,
    gender: null,
    about: null,
    birthday: null,
    status: 'active',
    created_at: '2022-02-21T08:07:08.000000Z',
    updated_at: null,
  },
  {
    id: '859c8cc5-4a5e-43a4-95b4-b28156c8831a',
    name: 'Owner',
    email: 'owner@yopmail.com',
    photo_url: null,
    role: {
      id: 5,
      name: 'Owner',
      slug: 'owner',
      permissions: [],
      description: null,
    },
    phone_number: null,
    gender: null,
    about: null,
    birthday: null,
    status: 'active',
    created_at: '2022-02-21T08:07:08.000000Z',
    updated_at: null,
  },
  {
    id: '601abb34-e9cd-4f97-8a90-6b6598388bb2',
    name: 'Tim Gudang 1',
    email: 'timgudang@yopmail.com',
    photo_url: null,
    role: {
      id: 3,
      name: 'Tim Gudang',
      slug: 'warehouse-team',
      permissions: [
        {
          id: 5,
          name: 'Lihat Inventory',
          code: 'READ_INVENTORY',
          description: null,
        },
        {
          id: 6,
          name: 'Buat Inventory',
          code: 'CREATE_INVENTORY',
          description: null,
        },
        {
          id: 7,
          name: 'Edit Inventory',
          code: 'UPDATE_INVENTORY',
          description: null,
        },
        {
          id: 8,
          name: 'Hapus Inventory',
          code: 'DELETE_INVENTORY',
          description: null,
        },
      ],
      description: null,
    },
    phone_number: null,
    gender: null,
    about: null,
    birthday: null,
    status: 'active',
    created_at: '2022-02-21T08:07:08.000000Z',
    updated_at: null,
  },
  {
    id: '55a29603-d122-4b28-bf7a-51c3973f7aa3',
    name: 'Cashier',
    email: 'cashier@yopmail.com',
    photo_url: null,
    role: {
      id: 7,
      name: 'Cashier',
      slug: 'cashier',
      permissions: [
        {
          id: 1,
          name: 'Lihat Jo',
          code: 'READ_JO',
          description: null,
        },
        {
          id: 3,
          name: 'Edit Jo',
          code: 'UPDATE_JO',
          description: null,
        },
      ],
      description: null,
    },
    phone_number: null,
    gender: null,
    about: null,
    birthday: null,
    status: 'active',
    created_at: '2022-02-21T08:07:09.000000Z',
    updated_at: null,
  },
];
