// prettier-ignore
enum UserActionTypes {
  SET_DIALOG_ADD_EDIT_USER_REQUESTED  = 'user/SET_DIALOG_ADD_EDIT_USER_REQUESTED',
  SET_DIALOG_ADD_EDIT_USER            = 'user/SET_DIALOG_ADD_EDIT_USER',
  SET_DIALOG_DETAIL_USER              = 'user/SET_DIALOG_DETAIL_USER',
  SET_DIALOG_PERMISSIONS_USER         = 'user/SET_DIALOG_PERMISSIONS_USER',

  FETCHING_USER_LIST_REQUESTED  = 'user/FETCHING_USER_LIST_REQUESTED',
  FETCHING_USER_LIST_LOADING    = 'user/FETCHING_USER_LIST_LOADING',
  FETCHING_USER_LIST_FAILURE    = 'user/FETCHING_USER_LIST_FAILURE',
  FETCHING_USER_LIST_SUCCESS    = 'user/FETCHING_USER_LIST_SUCCESS',

  FETCHING_USER_REQUESTED = 'user/FETCHING_USER_REQUESTED',
  FETCHING_USER_LOADING   = 'user/FETCHING_USER_LOADING',
  FETCHING_USER_FAILURE   = 'user/FETCHING_USER_FAILURE',
  FETCHING_USER_SUCCESS   = 'user/FETCHING_USER_SUCCESS',

  CREATE_USER_REQUESTED   = 'user/CREATE_USER_REQUESTED',
  CREATE_USER_LOADING     = 'user/CREATE_USER_LOADING',
  CREATE_USER_FAILURE     = 'user/CREATE_USER_FAILURE',
  CREATE_USER_SUCCESS     = 'user/CREATE_USER_SUCCESS',

  UPDATE_USER_REQUESTED   = 'user/UPDATE_USER_REQUESTED',
  UPDATE_USER_LOADING     = 'user/UPDATE_USER_LOADING',
  UPDATE_USER_FAILURE     = 'user/UPDATE_USER_FAILURE',
  UPDATE_USER_SUCCESS     = 'user/UPDATE_USER_SUCCESS',

  DELETE_USER_REQUESTED   = 'user/DELETE_USER_REQUESTED',
  DELETE_USER_LOADING     = 'user/DELETE_USER_LOADING',
  DELETE_USER_FAILURE     = 'user/DELETE_USER_FAILURE',
  DELETE_USER_SUCCESS     = 'user/DELETE_USER_SUCCESS',
}

export default UserActionTypes;
