export const SET_DRAWER_ADD_EDIT_CUSTOMER_REQUESTED = 'customer/SET_DRAWER_ADD_EDIT_CUSTOMER_REQUESTED';
export const SET_DRAWER_ADD_EDIT_CUSTOMER = 'customer/SET_DRAWER_ADD_EDIT_CUSTOMER';
export const SET_DIALOG_DETAIL_CUSTOMER = 'customer/SET_DIALOG_DETAIL_CUSTOMER';

export const FETCHING_CUSTOMER_LIST_REQUESTED = 'customer/FETCHING_CUSTOMER_LIST_REQUESTED';
export const FETCHING_CUSTOMER_LIST_LOADING = 'customer/FETCHING_CUSTOMER_LIST_LOADING';
export const FETCHING_CUSTOMER_LIST_FAILURE = 'customer/FETCHING_CUSTOMER_LIST_FAILURE';
export const FETCHING_CUSTOMER_LIST_SUCCESS = 'customer/FETCHING_CUSTOMER_LIST_SUCCESS';

export const FETCHING_CUSTOMER_REQUESTED = 'customer/FETCHING_CUSTOMER_REQUESTED';
export const FETCHING_CUSTOMER_LOADING = 'customer/FETCHING_CUSTOMER_LOADING';
export const FETCHING_CUSTOMER_FAILURE = 'customer/FETCHING_CUSTOMER_FAILURE';
export const FETCHING_CUSTOMER_SUCCESS = 'customer/FETCHING_CUSTOMER_SUCCESS';

export const CREATE_CUSTOMER_REQUESTED = 'customer/CREATE_CUSTOMER_REQUESTED';
export const CREATE_CUSTOMER_LOADING = 'customer/CREATE_CUSTOMER_LOADING';
export const CREATE_CUSTOMER_FAILURE = 'customer/CREATE_CUSTOMER_FAILURE';
export const CREATE_CUSTOMER_SUCCESS = 'customer/CREATE_CUSTOMER_SUCCESS';

export const UPDATE_CUSTOMER_REQUESTED = 'customer/UPDATE_CUSTOMER_REQUESTED';
export const UPDATE_CUSTOMER_LOADING = 'customer/UPDATE_CUSTOMER_LOADING';
export const UPDATE_CUSTOMER_FAILURE = 'customer/UPDATE_CUSTOMER_FAILURE';
export const UPDATE_CUSTOMER_SUCCESS = 'customer/UPDATE_CUSTOMER_SUCCESS';

export const DELETE_CUSTOMER_REQUESTED = 'customer/DELETE_CUSTOMER_REQUESTED';
export const DELETE_CUSTOMER_LOADING = 'customer/DELETE_CUSTOMER_LOADING';
export const DELETE_CUSTOMER_FAILURE = 'customer/DELETE_CUSTOMER_FAILURE';
export const DELETE_CUSTOMER_SUCCESS = 'customer/DELETE_CUSTOMER_SUCCESS';
