// prettier-ignore
enum AuthActionTypes {
  LOGIN_REQUESTED = 'auth/LOGIN_REQUESTED',
  LOGIN_LOADING   = 'auth/LOGIN_LOADING',
  LOGIN_SUCCESS   = 'auth/LOGIN_SUCCESS',
  LOGIN_FAILURE   = 'auth/LOGIN_FAILURE',

  REGISTER_REQUESTED  = 'auth/REGISTER_REQUESTED',
  REGISTER_LOADING    = 'auth/REGISTER_LOADING',
  REGISTER_SUCCESS    = 'auth/REGISTER_SUCCESS',
  REGISTER_FAILURE    = 'auth/REGISTER_FAILURE',

  LOGIN_WITH_SOCIAL_ACCOUNT_REQUESTED = 'auth/LOGIN_WITH_SOCIAL_ACCOUNT_REQUESTED',
  LOGIN_WITH_SOCIAL_ACCOUNT_LOADING   = 'auth/LOGIN_WITH_SOCIAL_ACCOUNT_LOADING',
  LOGIN_WITH_SOCIAL_ACCOUNT_FAILURE   = 'auth/LOGIN_WITH_SOCIAL_ACCOUNT_FAILURE',
  LOGIN_WITH_SOCIAL_ACCOUNT_SUCCESS   = 'auth/LOGIN_WITH_SOCIAL_ACCOUNT_SUCCESS',

  REVOKE_TOKEN_REQUESTED  = 'auth/REVOKE_TOKEN_REQUESTED',
  REVOKE_TOKEN_LOADING    = 'auth/REVOKE_TOKEN_LOADING',
  REVOKE_TOKEN_FAILURE    = 'auth/REVOKE_TOKEN_FAILURE',
  REVOKE_TOKEN_SUCCESS    = 'auth/REVOKE_TOKEN_SUCCESS',

  RESET_AUTH_STATE        = 'auth/RESET_AUTH_STATE',
}

export default AuthActionTypes;
